spring:
  application:
    name: zuulService
  profiles:
    active: prod
  cloud:
    enable: true
    config:
      uri: http://192.168.0.64:8888
      failFast: true
      retry:
        maxAttempts: 20
      label: master
      profile: prod